### PR TITLE
Make exist53 compatible

### PR DESCRIPTION
**Pull request by dizzzz**
added CI, not sure yet why it is not visible ; must probably be in target branch

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz Thanks this is good :-) Just wondering how we trigger the GitHub Actions. Also just for convention could you rename the GitHub Yaml file to "ci.yml" please

**Comment by dizzzz** [comment]
And i need to refer to v5.2.x ?

**Comment by dizzzz** [comment]
Afaik it is configured for each PR and change

**Comment by dizzzz** [comment]
@adamretter PR is reworked

**Comment by adamretter** [comment]
Yes it's in our Nexus repo... Let me find the URL

**Comment by dizzzz** [comment]
if it makes sense to point to a -SNAPSHOT.... how to trigger ?

**Comment by adamretter** [comment]
@dizzzz So i would suggest to add this to the `pom.xml`:

```xml
 <repositories>
        <repository>
            <id>exist-db-snapshots</id>
            <name>Evolved Binary - eXist-db Snapshots</name>
            <url>https://repo.evolvedbinary.com/repository/exist-db-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>exist-db</id>
            <name>Evolved Binary - eXist-db Releases</name>
            <url>https://repo.evolvedbinary.com/repository/exist-db/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
```

**Comment by dizzzz** [comment]
@adamretter done, thnx!

**Comment by adamretter** [comment]
@dizzzz Thank you :-)

**Pull request merged**
